-- Criação do esquema (schema)
CREATE SCHEMA IF NOT EXISTS DIRECTIONS_WEATHER;

-- Criação da tabela
CREATE TABLE IF NOT EXISTS DIRECTIONS_WEATHER.DIRECTIONS (
    CIDADE VARCHAR,
    ESTADO VARCHAR,
    ORIGEM VARCHAR(255),
    DESTINO VARCHAR(255),
    DISTANCIA_KM VARCHAR,
    MODO VARCHAR,
    TEMPO VARCHAR,
    LAT_INICIAL FLOAT,
    LNG_INICIAL FLOAT,
    LAT_FINAL FLOAT,
    LNG_FINAL FLOAT
);


CREATE TABLE  IF NOT EXISTS DIRECTIONS_WEATHER.FORECAST_WEATHER  (
    DATA VARCHAR,
    CIDADE VARCHAR,
    TEMPO VARCHAR,
    TEMPERATURA FLOAT,
    SENSACAO_TERMICA FLOAT,
    TEMPERATURA_MINIMA FLOAT,
    TEMPERATURA_MAXIMA FLOAT,
    UMIDADE INTEGER,
    PROBABILIDADE_CHUVA VARCHAR,
    PRECIPITACAO_3H_MM VARCHAR,
    LAT FLOAT,
    LNG FLOAT
);

CREATE TABLE  IF NOT EXISTS DIRECTIONS_WEATHER.CURRENT_WEATHER  (
    DATA VARCHAR,
    CIDADE VARCHAR,
    TEMPO VARCHAR,
    TEMPERATURA FLOAT,
    SENSACAO_TERMICA FLOAT,
    TEMPERATURA_MINIMA FLOAT,
    TEMPERATURA_MAXIMA FLOAT,
    UMIDADE INTEGER,
    PRECIPITACAO_1H_MM VARCHAR,
    PRECIPITACAO_3H_MM VARCHAR,
    LAT FLOAT,
    LNG FLOAT
);
                  


